module.exports = function (that) {
    that.copy('static-s/config.styl', 'static/source/stylus/main/config.styl')
    that.copy('static-s/init.styl', 'static/source/stylus/main/init.styl')
    that.copy('static-s/skeleton/button.styl', 'static/source/stylus/main/skeleton/button.styl')
    that.copy('static-s/skeleton/form.styl', 'static/source/stylus/main/skeleton/form.styl')
    that.copy('static-s/skeleton/init.styl', 'static/source/stylus/main/skeleton/init.styl')
    that.copy('static-s/skeleton/misc.styl', 'static/source/stylus/main/skeleton/misc.styl')
    that.copy('static-s/skeleton/prefixes.styl', 'static/source/stylus/main/skeleton/prefixes.styl')
    that.copy('static-s/skeleton/reset.styl', 'static/source/stylus/main/skeleton/reset.styl')
    that.copy('static-s/skeleton/grid/desktop.styl', 'static/source/stylus/main/skeleton/grid/desktop.styl')
    that.copy('static-s/skeleton/grid/init.styl', 'static/source/stylus/main/skeleton/grid/init.styl')
    that.copy('static-s/skeleton/grid/misc.styl', 'static/source/stylus/main/skeleton/grid/misc.styl')
    that.copy('static-s/skeleton/grid/phone.styl', 'static/source/stylus/main/skeleton/grid/phone.styl')
    that.copy('static-s/skeleton/grid/tablet.styl', 'static/source/stylus/main/skeleton/grid/tablet.styl')
    that.copy('static-s/skeleton/tags/a.styl', 'static/source/stylus/main/skeleton/tags/a.styl')
    that.copy('static-s/skeleton/tags/body.styl', 'static/source/stylus/main/skeleton/tags/body.styl')
    that.copy('static-s/skeleton/tags/em.styl', 'static/source/stylus/main/skeleton/tags/em.styl')
    that.copy('static-s/skeleton/tags/hr.styl', 'static/source/stylus/main/skeleton/tags/hr.styl')
    that.copy('static-s/skeleton/tags/htags.styl', 'static/source/stylus/main/skeleton/tags/htags.styl')
    that.copy('static-s/skeleton/tags/init.styl', 'static/source/stylus/main/skeleton/tags/init.styl')
    that.copy('static-s/skeleton/tags/lists.styl', 'static/source/stylus/main/skeleton/tags/lists.styl')
    that.copy('static-s/skeleton/tags/p.styl', 'static/source/stylus/main/skeleton/tags/p.styl')
    that.copy('static-s/skeleton/tags/small.styl', 'static/source/stylus/main/skeleton/tags/small.styl')
    that.copy('static-s/skeleton/tags/strong.styl', 'static/source/stylus/main/skeleton/tags/strong.styl')
    that.copy('static-s/skeleton/tags/table.styl', 'static/source/stylus/main/skeleton/tags/table.styl')
}